// js/medicos-data.js
const listDocs = [
  {
    id: 1,
    nomcompletos: "Dr. Felipe Artigas Sandalio",
    especialidad: "Cardiología",
    telefonono: "994455234",
    img: "img/fotos-clinica/1.jpg",
    correo: "fartigass@gmail.com",
    consultorio: "101",
  },
  {
    id: 2,
    nomcompletos: "Dra. Ana López Ramírez",
    especialidad: "Pediatría",
    telefonono: "984455123",
    correo: "alopezr@gmail.com",
    img: "img/fotos-clinica/4.jpg",
    consultorio: "102",
  },
  {
    id: 3,
    nomcompletos: "Dr. Diego Ramirez Pampallaupa",
    especialidad: "Dermatología",
    telefonono: "971455555",
    img: "img/fotos-clinica/2.jpg",
    correo: "dramirezp@gmail.com",
    consultorio: "103",
  },
  {
    id: 4,
    nomcompletos: "Dr. Carlos Ruiz Torres",
    especialidad: "Traumatología",
    telefonono: "992455765",
    img: "img/fotos-clinica/3.jpg",
    correo: "cruizt@gmail.com",
    consultorio: "104",
  },
  {
    id: 5,
    nomcompletos: "Dr. Renato Quinteca Valdiviezo",
    especialidad: "Odontología",
    telefonono: "982457653",
    img: "img/fotos-clinica/6.jpg",
    correo: "rquintecav@gmail.com",
    consultorio: "105",
  },
  {
    id: 6,
    nomcompletos: "Dra. Lorena Garcia Huamani",
    especialidad: "Ginecología",
    telefonono: "971231232",
    img: "img/fotos-clinica/5.jpg",
    correo: "alorenah@gmail.com",
    consultorio: "106",
  },
];
